### ISSUE TITLE
공학석사 학위 표시

### ISSUE THREAD

**Issue by Nimbus2002** [lonelywing/POSTECH_thesis_template_latex#6]
안녕하세요, 
postech-ucs.cls 파일에 368-369 line을 보면, 공학 석사도 Master of Science 로 표시 되게 되어있는데, 주석에는 M.E.라고 되어있어서, 혹시
`\ifthenelse{\equal{\@degreeField}{engineering}}
                {Master of Engineering}{}%           % 공학석사는 M.E.` 
라고 바꿔야하는 건 아닌지 문의 드립니다. 

![image](https://github.com/lonelywing/POSTECH_thesis_template_latex/assets/66589193/9b48ee76-8752-477e-99f4-2b7f436e5b08)

감사합니다.

**Comment by junetech** [comment]
이슈를 등록해 주셔서 감사합니다.

[대학원 학위논문 작성 지침](https://www.postech.ac.kr/wp-content/uploads/2017/08/%EB%8C%80%ED%95%99%EC%9B%90-%ED%95%99%EC%9C%84%EB%85%BC%EB%AC%B8-%EC%9E%91%EC%84%B1-%EC%A7%80%EC%B9%A8_2022.9.8_220920a.pdf)의 16페이지 예시에 Master of Science와 Doctor of Philosophy의 두 표현 밖에 없어서, 해당 cls파일에도 Master of Engineering의 표현이 반영되지 않은 것으로 같습니다.

[대학원 모집요강 영문 웹사이트의 instructions 페이지](https://adm-g.postech.ac.kr/ENG/admission/gist/?show=A)에서 "master's degree in medicine / science & engineering"이라는 표현이 사용되는 것이 확인되나,
공학 석사를 Master of Engineering이라고 표시하는 것이 맞는지에 대한 규정은 찾지 못했습니다.
학교측에 문의 후 확인되는 대로 수정하겠습니다.

**Comment by junetech** [comment]
[화학공학과 영문 홈페이지의 대학원 과정 소개 페이지](https://ce.postech.ac.kr/eng/eng2_2_2.php)에 "Master of Science"라는 표현이 사용되고, [Purdue의 파트너십 석사과정 소개 페이지](https://engineering.purdue.edu/ProMasters/programs-postech)에 "Master of Science in Engineering"이라는 표현이 사용됩니다.

바로 위에 올렸던 대학원 모집요강 영문 웹사이트에서 해당 표현이 사용된 맥락은 의과학대학원 박사과정 지원자격을 설명하기 위함이며, 학교에서 수여하는 학위 명칭을 설명하는 표현이 아닙니다.

공학 석사도 영문 학위 명칭으로 Master of Science를 사용하는 것이 맞는 것으로 보입니다. 이에 해당 issue를 닫습니다.
